var TELEPROMPTER_SCRIPT = [
  "ಒಂದು simple message.",
  "",
  "“Sorry, ಈ ಸಲ ಬರೋಕೆ ಆಗಲ್ಲ.”",
  "",
  "ಇಷ್ಟೇ.",
  "",
  "ಆದ್ರೆ ನೀವು ಆ ಒಂದು ಸಣ್ಣ messageನ ಪದೇ ಪದೇ type ಮಾಡಿ, delete ಮಾಡಿ, type ಮಾಡಿ, delete ಮಾಡಿ…",
  "",
  "ಕೊನೆಗೆ,",
  "",
  "“Okay, try ಮಾಡ್ತೀನಿ.”",
  "",
  "ಅಂತ message ಕಳಿಸಿಬಿಡ್ತೀರ.",
  "",
  "ಯಾಕೆ?",
  "",
  "ನಿಮಗೆ ನಿಜವಾಗಿಯೂ ಆ eventಗೆ ಹೋಗ್ಬೇಕು ಅಂತ ಅಲ್ಲ.",
  "",
  "ನಿಮಗೆ ಬೇಕಿರೋದು ಒಂದೇ —",
  "",
  "“ಇವ್ರು ನನ್ನ ಬಗ್ಗೆ ಕೆಟ್ಟದಾಗಿ ಅಂದುಕೊಳ್ಳಬಾರದು ಅಂತ.”",
  "",
  "ಇಲ್ಲಿ ಒಂದು interesting question ಇದೆ.",
  "",
  "ನಮ್ಮ ಜೀವನದಲ್ಲಿ ಅಷ್ಟೇನೂ important ಅಲ್ಲದ ಒಬ್ಬ ವ್ಯಕ್ತಿಗೆ ಕೂಡ…",
  "",
  "“ಇಲ್ಲ” ಅಂತ ಹೇಳೋಕೆ ನಾವು ಇಷ್ಟೊಂದು ಯಾಕೆ ಹೆದರ್ತೀವಿ?",
  "",
  "ನಮಸ್ಕಾರ, ನಾನು ಯುವರಾಜ್ — Welcome to UVISTIX WORDS.",
  "",
  "ಇವತ್ತು ಇದರ ಹಿಂದಿರೋ psychologyಯನ್ನ detail ಆಗಿ ಅರ್ಥ ಮಾಡ್ಕೊಳ್ಳೋಣ.",
  "",
  "ನಾವ್ಯಾಕೆ ಬೇರೆಯವರ approvalಗಾಗಿ ಇಷ್ಟೊಂದು effort ಹಾಕ್ತೀವಿ?",
  "",
  "ನಮ್ಮ decisions… ನಮ್ಮ mood… ಕೆಲವೊಮ್ಮೆ ನಮ್ಮ self-worth ಕೂಡ ಬೇರೆಯವರ reaction ಮೇಲೆ ಯಾಕೆ depend ಆಗುತ್ತೆ?",
  "",
  "ಈ ವಿಡಿಯೋ ಮುಗಿಯುವ ಹೊತ್ತಿಗೆ, ನೀವು ನಿಮ್ಮನ್ನೇ ಒಂದು ಸಣ್ಣ question ಕೇಳಿಕೊಳ್ಳಬಹುದು:",
  "",
  "“ನಾನು ಈ decision ತಗೊಳ್ತಿರೋದು ನನಗಿಷ್ಟ ಅಂತನಾ? ಅಥವಾ ಬೇರೆಯವರ ಕಣ್ಣಲ್ಲಿ ನಾನು ಚೆನ್ನಾಗಿ ಕಾಣ್ಬೇಕು ಅಂತನಾ?”",
  "",
  "ಒಮ್ಮೆ ನಿಮ್ಮ lifeನಲ್ಲೇ ನೋಡಿ.",
  "",
  "Officeನಲ್ಲಿ boss extra work ಕೊಟ್ರು. Already workload ಜಾಸ್ತಿ ಇದ್ರೂ, “Sure sir, ಮಾಡ್ತೀನಿ” ಅಂತೀರ.",
  "",
  "Group photoದಲ್ಲಿ ನೀವು ಚೆನ್ನಾಗಿ ಕಾಣ್ತಿಲ್ಲ ಅಂತ tension.",
  "",
  "Instagram post ಹಾಕಿದ ಮೇಲೆ ಪ್ರತಿ ಐದು ನಿಮಿಷಕ್ಕೆ likes check ಮಾಡೋದು.",
  "",
  "ಇದ್ರಲ್ಲಿ ಯಾವುದಾದರೂ ನಿಮಗೆ familiar ಅನಿಸಿದ್ರೆ…",
  "",
  "Trust me, ನೀವು ಒಬ್ಬರೇ ಅಲ್ಲ.",
  "",
  "ಇದಕ್ಕೆ psychologyಯಲ್ಲಿ ಒಂದು famous experiment ಇದೆ.",
  "",
  "1950sನಲ್ಲಿ psychologist Solomon Asch ಒಂದು study ಮಾಡಿದ್ರು.",
  "",
  "Participantsಗೆ very simple task: “ಇದರಲ್ಲಿ ಯಾವ line ಉದ್ದ ಇದೆ?” ಅಂತ ಕೇಳಿದ್ರು.",
  "",
  "Answer ಕಣ್ಣ ಮುಂದೆಯೇ ಇತ್ತು.",
  "",
  "ಆದ್ರೆ roomನಲ್ಲಿದ್ದ ಬೇರೆ actors intentionally wrong answer ಹೇಳೋಕೆ ಶುರುಮಾಡಿದ್ರು.",
  "",
  "ಈಗ ನಿಮ್ಮ turn. ನಿಮ್ಮ ಕಣ್ಣಿಗೆ correct answer ಕಾಣ್ತಿದೆ,",
  "ಆದ್ರೆ ಉಳಿದ ಎಲ್ಲರೂ wrong answer ಹೇಳ್ತಿದ್ದಾರೆ.",
  "",
  "ಏನ್ ಮಾಡ್ತೀರ?",
  "",
  "⏱ BEAT (1S)",
  "",
  "Interesting ವಿಷಯ ಏನಂದ್ರೆ… ಹಲವಾರು participants group ಹೇಳಿದ wrong answerನ್ನೇ follow ಮಾಡಿದ್ರು.",
  "",
  "ಯಾಕೆ ಗೊತ್ತಾ?",
  "",
  "Groupನಿಂದ different ಆಗಿ ಕಾಣಿಸಿಕೊಳ್ಳೋದು uncomfortable ಆಗಿತ್ತು.",
  "",
  "“ಎಲ್ಲರೂ ನನ್ನನ್ನೇ weird ಅಂತ ಅಂದುಕೊಂಡ್ರೆ?” ಅನ್ನೋ ಭಯ.",
  "",
  "Evolutionary psychology ಪ್ರಕಾರ, ಇದಕ್ಕೆ ಆಳವಾದ ಕಾರಣವಿದೆ.",
  "",
  "ಹಳೆಯ ಕಾಲದಲ್ಲಿ groupನಿಂದ reject ಆದ್ರೆ survival ಕಷ್ಟ ಇತ್ತು. Group ಅಂದ್ರೆ safety, food, life.",
  "",
  "ಇವತ್ತು ಯಾರಾದರೂ ನಿಮ್ಮ message ignore ಮಾಡಿದ್ರೆ survivalಗೆ ಏನೂ ತೊಂದರೆ ಆಗಲ್ಲ.",
  "",
  "ಆದ್ರೆ ನಿಮ್ಮ brainಗೆ ಅದು ಅದೇ ancient rejection threat ತರ feel ಆಗುತ್ತೆ.",
  "",
  "Leon Festinger ಅವರ “Social Comparison Theory” ಹೇಳುವಂತೆ — ನಾವು ನಮ್ಮನ್ನ evaluate ಮಾಡಿಕೊಳ್ಳೋಕೆ ಬೇರೆಯವರನ್ನ mirror ತರ use ಮಾಡ್ತೀವಿ.",
  "",
  "Approval ಸಿಕ್ಕಾಗ brainಗೆ ಸಿಗುವ ಆ ಸಣ್ಣ reward… ನಿಧಾನವಾಗಿ habit ಆಗಿ, ಕೊನೆಗೆ people-pleasing ಆಗಿ ಬದಲಾಗುತ್ತೆ.",
  "",
  "ಇಲ್ಲಿ ಒಂದು clear difference ಅರ್ಥ ಮಾಡ್ಕೋಬೇಕು.",
  "",
  "Approval ಬಯಸೋದು normal. Problem ಶುರುವಾಗೋದು approval ಸಿಗದಿದ್ದಾಗ “I am not good enough” ಅಂತ feel ಆದಾಗ.",
  "",
  "Kindness ಅಂದ್ರೆ ಇನ್ನೊಬ್ಬರ ಮೇಲೆ genuine ಕಾಳಜಿ.",
  "",
  "People-pleasing ಅಂದ್ರೆ “ಇವರು ನನ್ನನ್ನ bad person ಅಂತ ಅಂದುಕೊಳ್ತಾರೇನೋ” ಅನ್ನೋ fearನಿಂದ “Yes” ಹೇಳೋದು.",
  "",
  "ಹಾಗಾದ್ರೆ ಈ patternನಿಂದ ಹೊರಗೆ ಬರೋದು ಹೇಗೆ?",
  "",
  "1. Create a Pause",
  "",
  "ಯಾರಾದರೂ favour ಕೇಳಿದ ತಕ್ಷಣ automatic ಆಗಿ “ಹೌದು” ಅನ್ಬೇಡಿ.",
  "",
  "ಬದಲಿಗೆ:",
  "",
  "“ನಾನು schedule check ಮಾಡಿ a little timeನಲ್ಲಿ ಹೇಳ್ತೀನಿ.”",
  "",
  "ನಿಮ್ಮ automatic “Yes” ಮತ್ತು actual decision ಮಧ್ಯೆ ಒಂದು small gap create ಮಾಡಿ.",
  "",
  "2. Practice a Direct, Polite 'No'",
  "",
  "ಯಾವುದೇ unnecessary excuse ಕೊಡದೆ, simple ಆಗಿ reject ಮಾಡೋದನ್ನ practice ಮಾಡಿ:",
  "",
  "Thanks for asking, ಆದರೆ ಈ ಬಾರಿ ನನಗಿದು ಮಾಡಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ.",
  "",
  "Over-explain ಮಾಡೋ ಅಗತ್ಯವಿಲ್ಲ.",
  "",
  "3. Express Small Opinions",
  "",
  "ಒಂದು movie ಅಥವಾ food ಬಗ್ಗೆ groupನಲ್ಲಿ ಬೇರೆ opinion ಇದ್ರೆ, “ನನಗಂತೂ ಇದು average ಅನಿಸಿತು” ಅಂತ ನಿಮ್ಮ genuine voice share ಮಾಡೋದು start ಮಾಡಿ.",
  "",
  "ಒಂದು ಸಣ್ಣ truth ನೆನಪಿಡಿ.",
  "",
  "ನಾವು ಯಾರ approvalಗಾಗಿ stress ತಗೊಳ್ತೀವೋ… ಆ ವ್ಯಕ್ತಿ ನಮ್ಮ ಬಗ್ಗೆ 24 ಗಂಟೆ think ಮಾಡ್ತಿರಲ್ಲ.",
  "",
  "ಅವರು ತಮ್ಮ life, ತಮ್ಮ insecuritiesನಲ್ಲಿ busy ಆಗಿರ್ತಾರೆ.",
  "",
  "ಆ ಮೊದಲಿನ message ನೆನಪಿದೆಯಾ?",
  "",
  "ಮುಂದಿನ ಸಲ ಆ message type ಮಾಡುವಾಗ ನಿಮ್ಮನ್ನೇ ಕೇಳ್ಕೊಳ್ಳಿ:",
  "",
  "“ನಾನು ಈ decision ತಗೊಳ್ತಿರೋದು ನನಗಿಷ್ಟ ಅಂತನಾ? ಅಥವಾ ಬೇರೆಯವರ validationಗೋಸ್ಕರನಾ?”",
  "",
  "Approval ಬಯಸೋದು ತಪ್ಪಲ್ಲ, ಆದರೆ ನಿಮ್ಮ lifeನ steering wheel ಮಾತ್ರ ಯಾವತ್ತೂ ಇನ್ನೊಬ್ಬರ ಕೈಯಲ್ಲಿ ಇರಬಾರದು.",
  "",
  "Why We Think. Why We Feel. Why We Do.",
  "",
  "ಇಂಥ topics explore ಮಾಡೋದು ಇಷ್ಟ ಇದ್ರೆ — Subscribe ಮಾಡಿ, ಜೊತೆಗಿರಿ."
].join("\n");
