// PART 1: The Hook & Introduction
window.SCRIPT_PART_1 = [
  "Ond simple message.",
  "\"Sorry… ee sala barok-aagalla.\"",
  "Ashte.",
  "Aadre…",
  "aa message kalso-munche…",
  "pade pade type maadi…",
  "delete maad-ta-irtira.",
  "Mind… full confuse aagtirutte.",
  "Konege…",
  "\"Okay… nan baroke try maadtini…\"",
  "anta send maadi sumnagtira.",
  "Yaake?",
  "Nimage nijavaglu aa event-ge hogbeku anta enilla.",
  "Aadre…",
  "taleyalli irodu onde tension:",
  "\"Illa, aagalla\" anta direct aagi helbitre…",
  "ivru nan bagge enankotharo…",
  "anno tension!",
  "Ondu nimisha yochne maad-nodi.",
  "Nam life-ge ashtond important alda obba vyaktige…",
  "ondu simple \"No\" heloke…",
  "naav yaak ishtond tension tagoltivi?",
  "Yaak hedartivi?",
  "Hi, hello, Ellarigu Namaskara, naanu Yuvaraj.",
  "UVISTIX WORDS channel-ge tam elrigu swagatha.",
  "Ivattu…",
  "naav maatad-tirodu…",
  "nam-elrnu kaado… ondu common issue bagge:",
  "The Need for Approval.",
  "ಅಂದ್ರೆ… ಬೇರೆಯವರು ನಮ್ಮ ಬಗ್ಗೆ ಏನು ಅಂದ್ಕೊತಾರೆ ಅನ್ನೋ ಚಿಂತೆ!",
  "Bereyavr opinion…",
  "nam decisions mele…",
  "yaak ishtond effect aagutte?",
  "Kelavomme…",
  "nam mood kooda…",
  "bereyavru nam jothe hege behave maadtare annodr-mele depend aagoke shuru aagatte.",
  "Innu worst andre…",
  "nam bagge namage iro value kooda…",
  "bereyavru namna hege nodtare annodr-melene nintirutte.",
  "Ee video nodtiro ashtoo hothu…",
  "nim mind-nalli onde ondu question itkolli:",
  "\"Naanu ee decision tagoltirodu… nang-ista-anthana?",
  "Athva…",
  "bereyavar kannalli 'good person' anskolbeku anno uddesha-dindana?\""
].join("\n");

// PART 2: Real-Life Examples
window.SCRIPT_PART_2 = [
  "Neev office…",
  "athva friends circle-nalli notice maadiddira?",
  "Office-nalli:",
  "Colleague bandu…",
  "\"Bro, swalpa bega logout agtini, friends jote plans ide… ee work swalpa madkodtira?\"",
  "anta favour keldaga…",
  "Igaagle nimge work load jasti ide.",
  "Adru…",
  "mukad mel ond sanna smile itkondu…",
  "\"Sure bro\" anta helbidtira.",
  "Yaake?",
  "\"Aagalla bro sorry, ivatu nange already work load jasti ide\"…",
  "anta direct aagi helbitre…",
  "avrige bejar agbahudu…",
  "team-nalli nanna unsupportive ankobahudhu…",
  "anno bhaya!",
  "Social Media dalli:",
  "Ondu photo post maadtira.",
  "Prati 5 nimishakku ondsari.",
  "\"Estu likes bantu?",
  "Yar yar like madidare?",
  "Comment yaaru maadilva anta?\"",
  "Pade pade check maadti-irtira.",
  "Friends jothe:",
  "Ellaroo party plan maad-tidare.",
  "Nim pocket-nalli budget illa.",
  "Nimge hogoke interest-oo illa.",
  "Aadre…",
  "\"Ellaroo hogtidare…",
  "naanilla andre…",
  "nanna group-indane exclude maadbitre?\"",
  "anno bhayakke…",
  "kashta aadrusaha jothe hogtira.",
  "Idralli yavdadru ondu…",
  "nim life-nalli nadedidiya?",
  "Haagidre… trust me.",
  "Neevobbre alla.",
  "Nammella human minds hinge work aagodu."
].join("\n");

// PART 3: Psychological & Evolutionary Roots
window.SCRIPT_PART_3 = [
  "Actually…",
  "nam taleyalli bereyavara approval beku annoden hosa vishaya alla.",
  "Idanna artha maadkoloke…",
  "psychology-li ondu famous experiment ide.",
  "1950 ralli…",
  "Solomon Asch anno obba psychologist ondu simple test maadidru.",
  "Kelavu janaranna ondu room-nalli kursi…",
  "screen mele lines thorsi:",
  "\"Idralli yav line udda ide?\" anta keludru.",
  "Lines nodid takshana sanna magu kooda helbodu —",
  "yavdu udda ide anta.",
  "Ashtu simple task.",
  "Aadre… illi ondu twist ittu!",
  "Aa room-nalli idda thumba jana nijavada participants alla.",
  "Avaru experimenter plan maadidda actors!",
  "Avarige modle helidru:",
  "\"Neevellaro thappaada answer-ne helbeku\" anta.",
  "Obbobragi thappaada answer heloke start maadidru.",
  "Iga neev imagine maadkoli.",
  "Neeve aa room-nalli kootiddira.",
  "Nim kann-munde clear aagi kanstide —",
  "ellaroo heltiroraddu thappu anta.",
  "Aadre nim suttha iro ellaroo…",
  "full confidence inda onde wrong answer heltiddare.",
  "Ivaga…",
  "neeven maadtira?",
  "Nim correct answer heltira?",
  "Athva…",
  "ellaroo thappu heltiddaralla anta,",
  "avaranne follow maadi wrong answer heltira?",
  "Honest aagi yochne maadi.",
  "Shocking vishaya enandre…",
  "bahalashtu jana…",
  "group helida wrong answer-anne helidru!",
  "Yaak gotta?",
  "Answer gottirlilla anta alla.",
  "Group-ginta bere aagi nintukolloke avarige Sankocha agti-tu.",
  "\"Ellaroo onde answer heltiddare…",
  "naan maatra bere helidre…",
  "nanna weird ankondbitre?\"",
  "anno bhaya.",
  "Idar hinde…",
  "namma brain-na ondu deep Survival System ide.",
  "Hale kaaladalli manushya hege baduktidda anta imagine madkoli.",
  "Aagina kaaladalli obbane irodu andre… danger.",
  "Group jothe idrene safety.",
  "Food sigatte,",
  "protection sigatte,",
  "survival chances jasti.",
  "Haagagi…",
  "group-ninda reject aagodu andre,",
  "brain-ge direct threat tara feel aagtittu.",
  "Aadre… ivattu kaala badlagide.",
  "Yaaro nim message-ge reply maadlilla andre…",
  "athva colleague-ge \"No\" helidre…",
  "nim survival-ge enoo risk agalla.",
  "Aadre nam brain…",
  "innoo aa haleya pattern-nallene yochane maadtade.",
  "Adakke rejection andre rejection-e.",
  "Chikkadagirli, doddadagirli…",
  "yaaradroo namminda bejar aagi reject maadid thakshana…",
  "brain alert aagbidatte."
].join("\n");

// PART 4: Social Comparison & People-Pleasing Trap
window.SCRIPT_PART_4 = [
  "Innond interesting theory…",
  "Psychologist Leon Festinger helida Social Comparison Theory.",
  "Simple aagi helbekandre…",
  "nam bagge naavu judge maadkoloke,",
  "naavu bere janara jothe compare maadkoltivi.",
  "\"Naan chennagi kansti-dina?\"",
  "\"Naan life-nalli settle agidina?\"",
  "\"Naan avriginta munde idina?\"",
  "Idkella…",
  "pakkadalliro janaranna scale thara use maadtivi.",
  "Social media banda melantu idu innoo jaasti aagbitide.",
  "Yaaro vacation photo haaktare.",
  "Olle car, olle lifestyle nodtivi.",
  "Avella nodi nam life bagge namage doubts baroke shuru aagatte.",
  "Illinda main trap shuru aagodu nodi:",
  "Yaaro nam post-ge like maadi,",
  "\"Super aagi kanstiddira\" anta appreciate maadidaga…",
  "namma brain-ge ondu instant positive feel sigutte.",
  "\"Okay… naan ollevanu, jana nanna accept maadidare.\"",
  "Idanna brain repeated aagi expect maadoke shuru maadtade.",
  "Matte yaavaga approval sigalilvo…",
  "aavaga brain anxiety feel aagatte.",
  "Bereyavranna nodi compare maadodu…",
  "matte avarinda 'Olle anskoloke'",
  "namma self-respect-anne compromise maadkolodu…",
  "Illindane nodi shuru aagodu —",
  "PEOPLE-PLEASING!",
  "Approval bayasodu thappenalla.",
  "Ellarigoo appreciation beke beku.",
  "Namna yaaradroo appreciate madre yarig tane ishta aagalla heli?",
  "Problem yaavaga barutte andre…",
  "approval sigde iddaga,",
  "naavu nam value-ne doubt maadkoloke shuru maadidaga:",
  "\"Avaru reply maadlilla… andre avrige naanu important alwa?\"",
  "\"Avaru appreciate maadlilla… andre nanna effort waste-a?\"",
  "Illi ondu clear difference artha maadkoli:",
  "Kindness bere…",
  "People-Pleasing bere.",
  "Obbrige nijvaglu health problem ide…",
  "athva genuine emergency ide…",
  "nim kelsa bit-kooda avarige help maadtira andre…",
  "adu Kindness & Humanity.",
  "Aadre…",
  "avaru party-ge hogoke…",
  "nim kelsa jaasti maadtiddare…",
  "and \"Illa aagalla andre ivru nan bagge Thappaagi thilkolthare\" anno bhayadinda…",
  "nim schedule halu maadkothiralla…",
  "idu People-Pleasing.",
  "Kindness nim manasige shanthi kodatte.",
  "Aadre People-pleasing nimge unnecessary stress kodatte."
].join("\n");

// PART 5: 3 Actionable Solutions
window.SCRIPT_PART_5 = [
  "Haagidre… idrinda horage barodu hege?",
  "Daily life-nalli use maado thara",
  "3 simple steps heltini nodi:",
  "1. Thakshana \"Yes\" helbedi (The 5-Second Rule):",
  "Yaaradroo bandu unreasonable request kelid thakshana…",
  "reflex thara \"Ha sari, maadtini\" anta helbedi.",
  "Just ondu 5 seconds pause tagolli.",
  "\"Nanna plans check maadkondu heltini, swalpa time kodi\" anta heli.",
  "Ashte.",
  "Yaakandre…",
  "nim automatic \"Yes\" matte nim actual decision…",
  "iverdara madhye ondu small gap beku.",
  "Aa gap-nalli…",
  "nim mind-ge logic aagi yochane maadoke time sigutte.",
  "2. \"No\" heltira… 10 reasons kodbidi:",
  "Namage \"Illa\" anno maathu helbekadre,",
  "adanna defend maadoke 10 excuses ready itkothivi:",
  "\"Actually alli hogbekittu… health swalpa upset… mane kelsa ide…\"",
  "Ishtella explanations yaake?",
  "Direct aagi, polite aagi heli:",
  "\"Sorry bro, ivattu nanagoo plans ide, nan kayyalli manage maadok aagalla.\"",
  "Simple.",
  "allige-ne nillisi…",
  "jasti explaination beda.",
  "3. Sanna-putta vishayadalli nim choice heli (Micro-Decisions):",
  "Idu thumba useful habit.",
  "Group-nalli…",
  "ellaroo ondu movie super aagittu anta matadta idare.",
  "Nimge boring anstu.",
  "Slight aagi heli:",
  "\"Nimge ishta aaytha? Nanagantu ashtond connect aaglilla pa…\"",
  "Friends Ellaru dose order maadtidare.",
  "Nimge idli beku.",
  "Idli order maadi.",
  "Idu chikka vishaya anstbodu,",
  "aadre nim brain-ge ondu clear message hogatte:",
  "\"Nanna choice kooda matter aagutte anta.\""
].join("\n");

// PART 6: Reality Check & Outro
window.SCRIPT_PART_6 = [
  "Video mugiso munche… ondu honest reality check:",
  "Yaara approval-gaagi neevu ishtondu stress tagoltiddiro…",
  "aa vyakti nim bagge 24 hours yochne maadtiddara?",
  "Kandita illa!",
  "Avarige…",
  "avara life,",
  "avara commitments-allene time saalta illa.",
  "Avaru nim bagge yochane maado time-ginta…",
  "neevu avaru enankotaro…",
  "anta waste maado time-e thumba jaasti agirute.",
  "Mundina sala aa message type maad-tiralla…",
  "\"Sorry… ee sala barok-aagalla.\"",
  "Delete mado-munche…",
  "ondu second… NimmannE ond prashne kelkolli:",
  "\"Nan-idan-heltirOdu… nanagishta antana?\"",
  "Athava…",
  "\"Ivru nan bagge enandkoltare anno bhayadindana?\"",
  "Ee ondu question…",
  "nimma decisions bagge nimge tumba vishaya helbahudu.",
  "Yaakandre…",
  "Approval bayasod-tappalla.",
  "Navellaro bayastivi.",
  "Aadre…",
  "nim life-na steering wheel maatra…",
  "yaavattoo bereyavara kaiyalli irbardu.",
  "ನಮ್ಮ ಯೋಚನೆ.",
  "ನಮ್ಮ ಭಾವನೆ.",
  "ನಮ್ಮ ನಿರ್ಧಾರ.",
  "ಇಂಥ ವಿಷಯಗಳ ಬಗ್ಗೆ ಇನ್ನು ಆಳವಾಗಿ ತಿಳ್ಕೊಳ್ಳೋಕೆ —",
  "Subscribe to UVISTIX WORDS.",
  "ಕಲಿಯೋಣ, ಬೆಳೆಯೋಣ.",
  "ನಮಸ್ಕಾರ!"
].join("\n");
