/*
 * ============================================================
 * UVISTIX WORDS - TELEPROMPTER SCRIPT (STANDARDIZED TEMPO)
 * File: script.js
 * ============================================================
 */

/* ============================================================
   SCRIPT PART 1
   ============================================================ */

window.SCRIPT_PART_1 = [
  'Ondu simple message.',
  '',
  'Sorry...',
  'ee sala barok-aagalla.',
  '',
  'Ashte.',
  'Aadre...',
  '',
  'Aa message kalso-munche—',
  'pade pade type maadi...',
  'delete maad-ta-irtira.',
  '',
  'Mind... full confuse aagatte.',
  '',
  'Konege...',
  '"Okay, try maadtini"...',
  'anta send maadi sumnaagtira.',
  '',
  'Yaake?',
  '',
  'Nimage nijavaglu—',
  'alli hogbeku anta enilla.',
  '',
  'Aadre taleyalli...',
  'irode ONDE tension:',
  '',
  '"Illa... aagalla"—',
  'anta direct aagi helbitre...',
  'ivru nan bagge ENANKOTHARO...',
  'anno tension!',
  '',
  'Ondu nimisha yochne maadi.',
  '',
  'Nam life-ge—',
  'ashtond IMPORTANT ALDA vyaktige...',
  'ondu simple "NO" heloke...',
  'naav yaak ISHTOND tension tagoltivi?',
  '',
  'Yaak hedartivi?',
  '',
  'Hi, hello, ellarigu namaskara.',
  'Naanu Yuvaraj.',
  '',
  'UVISTIX WORDS channel-ge...',
  'tam elrigu swagatha.',
  '',
  'Ivattu naav maatad-tirodu...',
  'nam-elrnu kaado—',
  'ondu COMMON issue bagge:',
  '',
  'The Need for Approval.',
  '',
  'Andhre...',
  'ಬೇರೆಯವರು ನಮ್ಮ ಬಗ್ಗೆ...',
  'ಏನು ಅಂದ್ಕೊತಾರೆ...',
  'ಅನ್ನೋ ಚಿಂತೆ!',
  '',
  'Bereyavr opinion—',
  'nam decisions mele...',
  'yaak ishtond EFFECT aagatte?',
  '',
  'Kelavomme nam MOOD kooda—',
  'bereyavru nam jothe...',
  'hege behave maadtare...',
  'annodr mele DEPEND aagatte.',
  '',
  'Innu worst andre...',
  'nam bagge namagirva VALUE kooda—',
  'bereyavru namna HEGE nodtare...',
  'annodr melene nintirutte.',
  '',
  'Ee video nodtiro ashtoo hothu—',
  'nim mind-nalli...',
  'onde ondu QUESTION itkolli:',
  '',
  'Naanu ee decision tagoltirodu...',
  'NANG-ISTA anthana?',
  '',
  'Athva...',
  'bereyavar kannalli—',
  '"GOOD PERSON" anskolbeku...',
  'anno uddesha-dindana?'
].join('\n');


/* ============================================================
   SCRIPT PART 2
   ============================================================ */

window.SCRIPT_PART_2 = [
  'Neev office athva...',
  'friends circle-nalli notice maadiddira?',
  '',
  'Office-nalli...',
  'colleague obba bandu—',
  '"Bro, swalpa bega logout aagtini...',
  'friends jote plans ide...',
  'ee work swalpa maadkodtira?"...',
  '',
  'anta favour keldaga—',
  'igaagle nimge...',
  'WORK LOAD jaasti ide.',
  '',
  'Adru mukad mele—',
  'ond sanna smile itkondu...',
  '"Sure bro"...',
  'anta helbidtira.',
  '',
  'Yaake?',
  '',
  '"Aagalla bro sorry...',
  'ivattu already workload ide"—',
  'anta direct aagi helbitre...',
  'avrige BEJAR aagbahudu...',
  'team-nalli nanna...',
  'UNSUPPORTIVE ankobahudhu...',
  'anno bhaya!',
  '',
  'Social Media-dalli:',
  'Ondu photo post maadtira.',
  'Prati 5 nimishakku ondsari...',
  'estu likes bantu?',
  'Yaar-yaar like maadidare?',
  'Comment yaaru maadilva anta...',
  'pade pade check maadti-irtira.',
  '',
  'Friends jothe:',
  'Ellaroo party plan maad-tidare.',
  'Nim pocket-nalli budget illa.',
  'Nimge hogoke interest-oo illa.',
  '',
  'Aadre...',
  'ellaroo hogtidare—',
  'naan-illa andre...',
  'group-indane EXCLUDE maadbitre?',
  '',
  'Anno bhayakke...',
  'kashta aadrusaha jothe hogtira.',
  '',
  'Idralli yavdadru ondu—',
  'nim life-nalli NADEDIDIYA?',
  '',
  'Haagidre, trust me.',
  'Neevobbre alla.',
  'Nammella human minds...',
  'hinge WORK aagodu.'
].join('\n');


/* ============================================================
   SCRIPT PART 3
   ============================================================ */

window.SCRIPT_PART_3 = [
  'Actually...',
  'nam taleyalli...',
  'bereyavara approval beku annodu—',
  'en hosa vishaya alla.',
  '',
  'Idanna artha maadkoloke...',
  'psychology-li...',
  'ondu FAMOUS experiment ide.',
  '',
  '1950-ralli...',
  'Solomon Asch anno psychologist—',
  'ondu simple test maadidru.',
  '',
  'Kelavu janaranna...',
  'ondu room-nalli koodrisi...',
  'screen mele lines thorsi—',
  '"Idralli yav line udda ide?"...',
  'anta kelidru.',
  '',
  'Lines nodid takshana—',
  'sanna magu kooda helbodu...',
  'yavdu udda ide anta.',
  'Ashtu SIMPLE task.',
  '',
  'Aadre illi...',
  'ondu TWIST ittu!',
  '',
  'Aa room-nalli idda thumba jana—',
  'nijavada participants alla.',
  'Avaru experimenter...',
  'plan maadidda ACTORS!',
  '',
  'Avarige modle helidru:',
  'neevellaro thappaada—',
  'ANSWER-ne helbeku anta.',
  '',
  'Obbobragi...',
  'thappaada answer heloke...',
  'start maadidru.',
  '',
  'Iga imagine maadkoli.',
  'Neeve aa room-nalli kootiddira.',
  '',
  'Nim kann-munde...',
  'CLEAR aagi kanstide—',
  'ellaroo heltiroraddu thappu anta.',
  '',
  'Aadre nim suttha iro ellaroo...',
  'full CONFIDENCE inda...',
  'onde wrong answer heltiddare.',
  '',
  'Ivaga neeven maadtira?',
  '',
  'Nim correct answer heltira?',
  'Athva...',
  'ellaroo thappu heltiddaralla anta—',
  'avaranne follow maadi...',
  'WRONG answer heltira?',
  '',
  'Honest aagi yochne maadi.',
  '',
  'Shocking vishaya enandre...',
  'bahalashtu jana—',
  'group helida...',
  'wrong answer-anne helidru!',
  '',
  'Yaak gotta?',
  'Answer gottirlilla anta alla.',
  '',
  'Group-ginta bere aagi nilloke—',
  'avarige SANKOCHA aagtitthu.',
  '',
  '"Ellaroo onde answer heltiddare...',
  'naan maatra bere helidre...',
  'nanna WEIRD ankondbitre?"—',
  'anno bhaya.',
  '',
  'Idar hinde...',
  'namma brain-na...',
  'ondu deep SURVIVAL SYSTEM ide.',
  '',
  'Hale kaaladalli...',
  'manushya hege baduktidda—',
  'anta imagine maadkoli.',
  '',
  'Aagina kaaladalli...',
  'obbane irodu andre DANGER.',
  'Group jothe idrene SAFETY.',
  '',
  'Food sigatte...',
  'protection sigatte...',
  'survival chances jaasti.',
  '',
  'Haagagi...',
  'group-ninda reject aagodu andre—',
  'brain-ge DIRECT THREAT tara...',
  'feel aagtitthu.',
  '',
  'Aadre ivattu kaala badlagide.',
  '',
  'Yaaro reply maadlilla andre...',
  'athva colleague-ge "No" helidre...',
  'nim survival-ge enoo risk illa.',
  '',
  'Aadre nam brain—',
  'innoo aa HALEYA pattern-nallene...',
  'yochane maadtade.',
  '',
  'Adakke rejection andre REJECTION-E.',
  'Chikkadagirli, doddadagirli...',
  'yaaradroo namminda bejar aagi—',
  'reject maadid thakshana...',
  'brain ALERT aagbidatte.'
].join('\n');


/* ============================================================
   SCRIPT PART 4
   ============================================================ */

window.SCRIPT_PART_4 = [
  'Innond interesting theory...',
  'Psychologist Leon Festinger helida—',
  'Social Comparison Theory.',
  '',
  'Simple aagi helbekandre...',
  'nam bagge naavu judge maadkoloke—',
  'bere janara jothe...',
  'COMPARE maadkoltivi.',
  '',
  '"Naan chennagi kansti-dina?',
  'Naan life-nalli settle aagidina?',
  'Naan avriginta munde idina?"...',
  '',
  'Idkella pakkadalliro janaranna—',
  'SCALE thara use maadtivi.',
  '',
  'Social media banda melantu—',
  'idu innoo JAASTI aagbitide.',
  '',
  'Yaaro vacation photo haaktare.',
  'Olle car, olle lifestyle nodtivi.',
  'Avella nodi nam life bagge...',
  'namage DOUBTS baroke shuru aagatte.',
  '',
  'Illinda main trap nodi:',
  'Yaaro nam post-ge like maadi...',
  '"Super aagi kanstiddira"...',
  'anta appreciate maadidaga—',
  'brain-ge instant POSITIVE feel sigatte.',
  '',
  '"Okay, naan ollevanu...',
  'jana nanna ACCEPT maadidare."',
  '',
  'Idanna brain repeated aagi—',
  'EXPECT maadoke shuru maadtade.',
  '',
  'Matte yaavaga approval sigalilvo...',
  'aavaga brain ANXIETY feel aagatte.',
  '',
  'Bereyavranna nodi compare maadodu...',
  'matte avarinda "OLLE ANSEEKOKE"—',
  'namma self-respect-anne...',
  'compromise maadkolodu...',
  '',
  'Illindane nodi shuru aagodu—',
  'PEOPLE-PLEASING!',
  '',
  'Approval bayasodu thappenalla.',
  'Ellarigoo APPRECIATION beke beku.',
  'Namna yaaradroo mecchidre...',
  'yaarig tane ishta aagalla heli?',
  '',
  'Problem yaavaga barutte andre...',
  'approval sigde iddaga—',
  'naavu nam VALUE-ne...',
  'doubt maadkoloke shuru maadidaga:',
  '',
  '"Avaru reply maadlilla...',
  'andre avrige naanu important alwa?',
  'Avaru appreciate maadlilla...',
  'andre nanna EFFORT waste-a?"',
  '',
  'Illi ondu clear difference...',
  'artha maadkoli:',
  '',
  'Kindness bere...',
  'People-Pleasing bere.',
  '',
  'Obbrige genuine emergency ide...',
  'nim kelsa bittu kooda—',
  'avarige help maadtira andre...',
  'adu KINDNESS and humanity.',
  '',
  'Aadre...',
  'avaru party-ge hogoke...',
  'nim kelsa jaasti maadtiddare...',
  'matte "Illa andre...',
  'thappaagi thilkolthare" anno bhayadinda—',
  'nim schedule halu maadkothiralla...',
  'idu PEOPLE-PLEASING.',
  '',
  'Kindness nim manasige shanthi kodatte.',
  'People-pleasing unnecessary STRESS kodatte.'
].join('\n');


/* ============================================================
   SCRIPT PART 5
   ============================================================ */

window.SCRIPT_PART_5 = [
  'Haagidre idrinda...',
  'horage barodu hege?',
  '',
  'Daily life-nalli use maado thara—',
  '3 SIMPLE STEPS heltini nodi:',
  '',
  '1. Thakshana "Yes" helbedi—',
  'The 5-Second Rule.',
  '',
  'Yaaradroo bandu...',
  'unreasonable request kelid takshana—',
  'reflex thara "Ha sari maadtini"...',
  'anta helbedi.',
  '',
  'Just ondu 5 SECONDS pause tagolli.',
  '"Nanna plans check maadi heltini...',
  'swalpa time kodi" anta heli.',
  'Ashte.',
  '',
  'Yaakandre...',
  'nim automatic "Yes" matte...',
  'nim actual decision-na madhye—',
  'ondu SMALL GAP beku.',
  '',
  'Aa gap-nalli...',
  'nim mind-ge LOGIC aagi...',
  'yochane maadoke time sigutte.',
  '',
  '2. "No" heltira...',
  '10 reasons kodbidi.',
  '',
  'Namage "Illa" anno maathu helbekadre—',
  'adanna defend maadoke...',
  '10 excuses ready itkothivi:',
  '',
  '"Alli hogbekittu...',
  'health swalpa upset...',
  'mane kelsa ide"...',
  '',
  'Ishtella explanations yaake?',
  'Direct aagi, polite aagi heli:',
  '',
  '"Sorry bro, ivattu plans ide...',
  'nan kayyalli manage maadok aagalla."',
  '',
  'Simple.',
  'Allige-ne nillisi...',
  'jaasti EXPLANATION beda.',
  '',
  '3. Sanna-putta vishayadalli...',
  'nim choice heli:',
  'Micro-Decisions.',
  '',
  'Idu thumba USEFUL habit.',
  '',
  'Group-nalli ellaroo...',
  'ondu movie super antha matadtidare.',
  'Nimge BORING anstu.',
  '',
  'Slight aagi heli:',
  '"Nimge ishta aaytha?...',
  'Nanagantu ashtond connect aaglilla pa."',
  '',
  'Friends ellaru dose order maadtidare.',
  'Nimge IDLI beku.',
  'Idli order maadi.',
  '',
  'Idu chikka vishaya anstbodu.',
  'Aadre nim brain-ge—',
  'ondu CLEAR MESSAGE hogatte:',
  '"Nanna choice kooda matter aagutte" anta.'
].join('\n');


/* ============================================================
   SCRIPT PART 6
   ============================================================ */

window.SCRIPT_PART_6 = [
  'Video mugiso munche...',
  'ondu honest REALITY CHECK:',
  '',
  'Yaara approval-gaagi—',
  'neevu ishtondu stress tagoltiddiro...',
  'aa vyakti nim bagge...',
  '24 hours yochne maadtiddara?',
  '',
  'Kandita illa!',
  '',
  'Avarige avara life...',
  'avara commitments-allene...',
  'time saalta illa.',
  '',
  'Avaru nim bagge yochane maado time-ginta—',
  'neevu "Avaru enankotaro" anta...',
  'WASTE maado time-e thumba jaasti.',
  '',
  'Mundina sala aa message type maadi...',
  '"Sorry, ee sala barok-aagalla"...',
  'delete mado-munche...',
  'ondu second NIMMANNE kelkolli:',
  '',
  'Naan idan heltirOdu...',
  'NANG-ISHTA antana?',
  '',
  'Athava...',
  '"Ivru enandkoltare" anno...',
  'BHAYADINDANA?',
  '',
  'Ee ondu question...',
  'nimma decisions bagge...',
  'nimge thumba vishaya helutte.',
  '',
  'Yaakandre approval bayasodu tappalla.',
  'Navellaro bayastivi.',
  '',
  'Aadre nim life-na STEERING WHEEL maatra—',
  'yaavattoo bereyavara kaiyalli irbardu.',
  '',
  'ನಮ್ಮ ಯೋಚನೆ.',
  'ನಮ್ಮ ಭಾವನೆ.',
  'ನಮ್ಮ ನಿರ್ಧಾರ.',
  '',
  'ಇಂಥ ವಿಷಯಗಳ ಬಗ್ಗೆ...',
  'ಇನ್ನು ಆಳವಾಗಿ ತಿಳ್ಕೊಳ್ಳೋಕೆ—',
  'SUBSCRIBE to UVISTIX WORDS.',
  '',
  'ಕಲಿಯೋಣ, ಬೆಳೆಯೋಣ.',
  'ನಮಸ್ಕಾರ!'
].join('\n');

/* ============================================================
   SIMPLE LOAD TEST
   ============================================================ */

window.UVISTIX_SCRIPT_READY = true;
